version: "3.8"

services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000/ws

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - media-service
    environment:
      - MEDIA_SERVICE_URL=http://media-service:5000
      - MEDIA_SERVICE_GRPC_HOST=media-service:50051

  media-service:
    build:
      context: ./media-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # REST API
      - "50051:50051" # gRPC
